---
# tasks file for deploy grafana

- name: Install nessesary package
  apt: 
      name: apt-transport-https
      state: present
      update_cache: yes
  become: yes

- name: add grafana gpg key
  shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -

- name: add grafana repo 
  apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: grafana
  become: yes

- name: Update apt
  apt: update_cache=yes
  become: true
  
- name: Install grafana
  apt: 
      name: grafana
      state: present
      update_cache: yes
  become: yes

- name: Enable and start grafana service
  service:
    name: grafana-server
    enabled: yes
    state: started
  become: yes

## for building a dev environment

# INSTALL NVM, NODE 14

# - name: Setup Node
#   become: yes
#   become_flags: -i # Execute config files such as .profile (Ansible uses non-interactive login shells)
#   become_user: runner
#   block:
#     - name: Install nvm
#       ansible.builtin.shell: >
#         curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash
#       args:
#         executable: /bin/bash
#         chdir: "$HOME"
#         creates: "$HOME/.nvm/nvm.sh"

#     - name: Setup .profile
#       ansible.builtin.lineinfile:
#         path: ~/.profile
#         line: source ~/.nvm/nvm.sh # This will make sure Node is on the user's PATH
#         create: yes

#     - name: Install node
#       ansible.builtin.shell: |
#         nvm install {{item}}
#       args:
#         executable: /bin/bash
#         chdir: "$HOME"
#         creates: "$HOME/.nvm/versions/node/v{{item}}"
#       loop:
#         - 14.15.0




# wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.38.0/install.sh | bash
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# nvm install --lts

# install yarn
# npm install --global yarn

#INSTALL GO (AND BUILD ESSENTIALS AND MAKE?)
# sudo snap install go --classic
# sudo apt-get install build-essential
# sudo apt install make

# CLONE GRAFANA REPO AND MOVE INSIDE
# git clone https://github.com/grafana/grafana.git
# cd grafana/
   
# RAISE OPEN FILE LIMIT
# ulimit -S -n 2048
      
# START ENV
# yarn install --pure-lockfile
# yarn start
# make run
