---

- name: Install Prerequisites
  apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

# Sudo Group Setup
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'

# User + Key Setup
- name: Create a new regular user with sudo privileges
  user:
    name: "{{ create_user }}"
    state: present
    groups: wheel
    append: true
    create_home: true
    shell: /bin/bash

- name: Set authorized key for remote user
  ansible.posix.authorized_key:
    user: "{{ create_user }}"
    state: present
    key: "{{ copy_local_key }}"

- name: Disable password authentication for root
  lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    regexp: '^#?PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
# switch to sudo user here
# Install Packages
- name: Update apt
  apt: update_cache=yes
  become: true

- name: Install required system packages
  apt: name={{ sys_packages }} state=latest
  become: true

# UFW Setup
- name: UFW - Allow SSH connections
  community.general.ufw:
    rule: allow
    name: OpenSSH
  become: true

- name: UFW - Open port for Grafana
  community.general.ufw:
    rule: allow
    port: 3000
  become: true

- name: UFW - Deny all other incoming traffic by default
  community.general.ufw:
    state: enabled
    policy: deny
    direction: incoming
  become: true